name: Continuous Delivery (fluvio.io)

on:
  push:
    tags:
      - 'v*'
    branches-ignore:
      - '**'

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  release:
    name: Release
    uses: ./.github/workflows/release-prod.yml
    permissions:
      contents: write
      deployments: write
      id-token: write

  deploy:
    name: Deploy
    needs: release
    uses: ./.github/workflows/deploy.yml
    permissions:
      contents: write
      deployments: write
      id-token: write
    secrets:
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
    with:
      project_name: fluvio-docs-prod
