name: Continuous Integration

on:
  pull_request:
    branches: [main]

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  integrity:
    name: Integrity Checks
    runs-on: ubuntu-latest
    permissions:
      contents: write
      deployments: write
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Setup NodeJS
        uses: actions/setup-node@v4

      - name: Install Dependencies
        run: npm ci

      - name: Build for Production
        env:
          NODE_ENV: production
        run: npm run build
