name: Deploy

on:
  workflow_call:
    inputs:
      project_name:
        type: string
        required: true
        default: 'Cloudflare Pages Project Name'
    secrets:
      CLOUDFLARE_ACCOUNT_ID:
        required: true
      CLOUDFLARE_API_TOKEN:
        required: true

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: write
      deployments: write
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4

      - name: Install Dependencies
        run: npm ci

      - name: Build for Production
        env:
          NODE_ENV: production
        run: npm run build

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          directory: ./build
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          projectName: ${{ inputs.project_name }}
          branch: 'main'
